services:
  prod-intra:
    build:
      context: .
      dockerfile : Dockerfile-prod-intra
    tty : true
    environment:
      - BASE_URL=http://localhost:81
    volumes:
     # - ./docker-dev-volumes:/vars
     # - ./docker-dev-volumes/php:/usr/local/etc/php
     # - ./docker-dev-volumes/apache2:/etc/apache2
      - ./prod-intra-brin:/var/www
      - ./prod-intra-brin/public:/var/www/html
    ports:
      - 91:80
  next-intra:
    build:
      context: .
      dockerfile : Dockerfile-next-intra
    tty : true
    command : "npm run dev"
    environment:
      - BASE_URL=http://localhost:81
    volumes:
      - ./intra-next:/app
    ports:
      - 81:3000    