services:
  prod-intra:
    build:
      context: .
      dockerfile : Dockerfile-prod-intra
    tty : true
    environment:
      - BASE_URL=http://localhost:81
    volumes:
     # - ./docker-dev-volumes:/vars
     # - ./docker-dev-volumes/php:/usr/local/etc/php
     # - ./docker-dev-volumes/apache2:/etc/apache2
      - ./prod-intra:/var/www
      - ./prod-intra/public:/var/www/html
    ports:
      - 91:80